name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: pnpm
    - name: Install package and build
      run: |
        pnpm install --frozen-lockfile
        pnpm build
        tar zcvf dist.tar.gz dist
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: x86-64
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        name: public
        tag_name: master
        files: |
          ./dist.tar.gz
